apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestlistdeploy
  labels:
    app: guestlist-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      the-app-is: guestlist-pod
  template:
    metadata:
      labels:
        the-app-is: guestlist-pod
    spec:
      containers:
      - name: guestlistcontainer
        image: giligalili/guestlistapi:ver04

 
